// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLHTM0_HzugwJQ_9eK_3jti-yaNSej41c',
    appId: '1:377494884598:web:9dcbb2135d09f23177dcd7',
    messagingSenderId: '377494884598',
    projectId: 'resta-3aac0',
    authDomain: 'resta-3aac0.firebaseapp.com',
    storageBucket: 'resta-3aac0.appspot.com',
    measurementId: 'G-VTYJCK9ZMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq12OdsVdzFmAcGNfHjW1Mm3kJEMYakhQ',
    appId: '1:377494884598:android:d9abd413115cc68877dcd7',
    messagingSenderId: '377494884598',
    projectId: 'resta-3aac0',
    storageBucket: 'resta-3aac0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnMGsSbz4uYa0Y-PGoX7tb-xtUBj9Jrwc',
    appId: '1:377494884598:ios:19d4f5a28058f4f577dcd7',
    messagingSenderId: '377494884598',
    projectId: 'resta-3aac0',
    storageBucket: 'resta-3aac0.appspot.com',
    iosClientId: '377494884598-1d4eamcpr9baj6hlt6dp1cou8qjqt9bh.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnMGsSbz4uYa0Y-PGoX7tb-xtUBj9Jrwc',
    appId: '1:377494884598:ios:9312113c91bbe33777dcd7',
    messagingSenderId: '377494884598',
    projectId: 'resta-3aac0',
    storageBucket: 'resta-3aac0.appspot.com',
    iosClientId: '377494884598-8gjm2c9v8u1n4g8siuq8q0i7ffaoticv.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
